name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 8.x
                  include-prerelease: true

            - name: Publish .NET Core Project
              run: dotnet publish TestForPWA/TestForPWA.csproj -c Release -o release --nologo

            - name: copy index.html to 404.html
              run: cp release/wwwroot/index.html release/wwwroot/404.html

            - name: Add .nojekyll file
              run: touch release/wwwroot/.nojekyll
